require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgenciaController do

  # This should return the minimal set of attributes required to create a valid
  # Agencium. As you add validations to Agencium, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgenciaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all agencia as @agencia" do
      agencium = Agencium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:agencia).should eq([agencium])
    end
  end

  describe "GET show" do
    it "assigns the requested agencium as @agencium" do
      agencium = Agencium.create! valid_attributes
      get :show, {:id => agencium.to_param}, valid_session
      assigns(:agencium).should eq(agencium)
    end
  end

  describe "GET new" do
    it "assigns a new agencium as @agencium" do
      get :new, {}, valid_session
      assigns(:agencium).should be_a_new(Agencium)
    end
  end

  describe "GET edit" do
    it "assigns the requested agencium as @agencium" do
      agencium = Agencium.create! valid_attributes
      get :edit, {:id => agencium.to_param}, valid_session
      assigns(:agencium).should eq(agencium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Agencium" do
        expect {
          post :create, {:agencium => valid_attributes}, valid_session
        }.to change(Agencium, :count).by(1)
      end

      it "assigns a newly created agencium as @agencium" do
        post :create, {:agencium => valid_attributes}, valid_session
        assigns(:agencium).should be_a(Agencium)
        assigns(:agencium).should be_persisted
      end

      it "redirects to the created agencium" do
        post :create, {:agencium => valid_attributes}, valid_session
        response.should redirect_to(Agencium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agencium as @agencium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agencium.any_instance.stub(:save).and_return(false)
        post :create, {:agencium => {}}, valid_session
        assigns(:agencium).should be_a_new(Agencium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agencium.any_instance.stub(:save).and_return(false)
        post :create, {:agencium => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agencium" do
        agencium = Agencium.create! valid_attributes
        # Assuming there are no other agencia in the database, this
        # specifies that the Agencium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Agencium.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => agencium.to_param, :agencium => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested agencium as @agencium" do
        agencium = Agencium.create! valid_attributes
        put :update, {:id => agencium.to_param, :agencium => valid_attributes}, valid_session
        assigns(:agencium).should eq(agencium)
      end

      it "redirects to the agencium" do
        agencium = Agencium.create! valid_attributes
        put :update, {:id => agencium.to_param, :agencium => valid_attributes}, valid_session
        response.should redirect_to(agencium)
      end
    end

    describe "with invalid params" do
      it "assigns the agencium as @agencium" do
        agencium = Agencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => agencium.to_param, :agencium => {}}, valid_session
        assigns(:agencium).should eq(agencium)
      end

      it "re-renders the 'edit' template" do
        agencium = Agencium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agencium.any_instance.stub(:save).and_return(false)
        put :update, {:id => agencium.to_param, :agencium => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agencium" do
      agencium = Agencium.create! valid_attributes
      expect {
        delete :destroy, {:id => agencium.to_param}, valid_session
      }.to change(Agencium, :count).by(-1)
    end

    it "redirects to the agencia list" do
      agencium = Agencium.create! valid_attributes
      delete :destroy, {:id => agencium.to_param}, valid_session
      response.should redirect_to(agencia_url)
    end
  end

end
