require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnderecobrasileirosController do

  # This should return the minimal set of attributes required to create a valid
  # Enderecobrasileiro. As you add validations to Enderecobrasileiro, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnderecobrasileirosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enderecobrasileiros as @enderecobrasileiros" do
      enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enderecobrasileiros).should eq([enderecobrasileiro])
    end
  end

  describe "GET show" do
    it "assigns the requested enderecobrasileiro as @enderecobrasileiro" do
      enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
      get :show, {:id => enderecobrasileiro.to_param}, valid_session
      assigns(:enderecobrasileiro).should eq(enderecobrasileiro)
    end
  end

  describe "GET new" do
    it "assigns a new enderecobrasileiro as @enderecobrasileiro" do
      get :new, {}, valid_session
      assigns(:enderecobrasileiro).should be_a_new(Enderecobrasileiro)
    end
  end

  describe "GET edit" do
    it "assigns the requested enderecobrasileiro as @enderecobrasileiro" do
      enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
      get :edit, {:id => enderecobrasileiro.to_param}, valid_session
      assigns(:enderecobrasileiro).should eq(enderecobrasileiro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enderecobrasileiro" do
        expect {
          post :create, {:enderecobrasileiro => valid_attributes}, valid_session
        }.to change(Enderecobrasileiro, :count).by(1)
      end

      it "assigns a newly created enderecobrasileiro as @enderecobrasileiro" do
        post :create, {:enderecobrasileiro => valid_attributes}, valid_session
        assigns(:enderecobrasileiro).should be_a(Enderecobrasileiro)
        assigns(:enderecobrasileiro).should be_persisted
      end

      it "redirects to the created enderecobrasileiro" do
        post :create, {:enderecobrasileiro => valid_attributes}, valid_session
        response.should redirect_to(Enderecobrasileiro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enderecobrasileiro as @enderecobrasileiro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enderecobrasileiro.any_instance.stub(:save).and_return(false)
        post :create, {:enderecobrasileiro => {}}, valid_session
        assigns(:enderecobrasileiro).should be_a_new(Enderecobrasileiro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enderecobrasileiro.any_instance.stub(:save).and_return(false)
        post :create, {:enderecobrasileiro => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enderecobrasileiro" do
        enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
        # Assuming there are no other enderecobrasileiros in the database, this
        # specifies that the Enderecobrasileiro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enderecobrasileiro.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => enderecobrasileiro.to_param, :enderecobrasileiro => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested enderecobrasileiro as @enderecobrasileiro" do
        enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
        put :update, {:id => enderecobrasileiro.to_param, :enderecobrasileiro => valid_attributes}, valid_session
        assigns(:enderecobrasileiro).should eq(enderecobrasileiro)
      end

      it "redirects to the enderecobrasileiro" do
        enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
        put :update, {:id => enderecobrasileiro.to_param, :enderecobrasileiro => valid_attributes}, valid_session
        response.should redirect_to(enderecobrasileiro)
      end
    end

    describe "with invalid params" do
      it "assigns the enderecobrasileiro as @enderecobrasileiro" do
        enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enderecobrasileiro.any_instance.stub(:save).and_return(false)
        put :update, {:id => enderecobrasileiro.to_param, :enderecobrasileiro => {}}, valid_session
        assigns(:enderecobrasileiro).should eq(enderecobrasileiro)
      end

      it "re-renders the 'edit' template" do
        enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enderecobrasileiro.any_instance.stub(:save).and_return(false)
        put :update, {:id => enderecobrasileiro.to_param, :enderecobrasileiro => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enderecobrasileiro" do
      enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
      expect {
        delete :destroy, {:id => enderecobrasileiro.to_param}, valid_session
      }.to change(Enderecobrasileiro, :count).by(-1)
    end

    it "redirects to the enderecobrasileiros list" do
      enderecobrasileiro = Enderecobrasileiro.create! valid_attributes
      delete :destroy, {:id => enderecobrasileiro.to_param}, valid_session
      response.should redirect_to(enderecobrasileiros_url)
    end
  end

end
