require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TabelageralsController do

  # This should return the minimal set of attributes required to create a valid
  # Tabelageral. As you add validations to Tabelageral, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TabelageralsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tabelagerals as @tabelagerals" do
      tabelageral = Tabelageral.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tabelagerals).should eq([tabelageral])
    end
  end

  describe "GET show" do
    it "assigns the requested tabelageral as @tabelageral" do
      tabelageral = Tabelageral.create! valid_attributes
      get :show, {:id => tabelageral.to_param}, valid_session
      assigns(:tabelageral).should eq(tabelageral)
    end
  end

  describe "GET new" do
    it "assigns a new tabelageral as @tabelageral" do
      get :new, {}, valid_session
      assigns(:tabelageral).should be_a_new(Tabelageral)
    end
  end

  describe "GET edit" do
    it "assigns the requested tabelageral as @tabelageral" do
      tabelageral = Tabelageral.create! valid_attributes
      get :edit, {:id => tabelageral.to_param}, valid_session
      assigns(:tabelageral).should eq(tabelageral)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tabelageral" do
        expect {
          post :create, {:tabelageral => valid_attributes}, valid_session
        }.to change(Tabelageral, :count).by(1)
      end

      it "assigns a newly created tabelageral as @tabelageral" do
        post :create, {:tabelageral => valid_attributes}, valid_session
        assigns(:tabelageral).should be_a(Tabelageral)
        assigns(:tabelageral).should be_persisted
      end

      it "redirects to the created tabelageral" do
        post :create, {:tabelageral => valid_attributes}, valid_session
        response.should redirect_to(Tabelageral.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tabelageral as @tabelageral" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tabelageral.any_instance.stub(:save).and_return(false)
        post :create, {:tabelageral => {}}, valid_session
        assigns(:tabelageral).should be_a_new(Tabelageral)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tabelageral.any_instance.stub(:save).and_return(false)
        post :create, {:tabelageral => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tabelageral" do
        tabelageral = Tabelageral.create! valid_attributes
        # Assuming there are no other tabelagerals in the database, this
        # specifies that the Tabelageral created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tabelageral.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tabelageral.to_param, :tabelageral => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tabelageral as @tabelageral" do
        tabelageral = Tabelageral.create! valid_attributes
        put :update, {:id => tabelageral.to_param, :tabelageral => valid_attributes}, valid_session
        assigns(:tabelageral).should eq(tabelageral)
      end

      it "redirects to the tabelageral" do
        tabelageral = Tabelageral.create! valid_attributes
        put :update, {:id => tabelageral.to_param, :tabelageral => valid_attributes}, valid_session
        response.should redirect_to(tabelageral)
      end
    end

    describe "with invalid params" do
      it "assigns the tabelageral as @tabelageral" do
        tabelageral = Tabelageral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tabelageral.any_instance.stub(:save).and_return(false)
        put :update, {:id => tabelageral.to_param, :tabelageral => {}}, valid_session
        assigns(:tabelageral).should eq(tabelageral)
      end

      it "re-renders the 'edit' template" do
        tabelageral = Tabelageral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tabelageral.any_instance.stub(:save).and_return(false)
        put :update, {:id => tabelageral.to_param, :tabelageral => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tabelageral" do
      tabelageral = Tabelageral.create! valid_attributes
      expect {
        delete :destroy, {:id => tabelageral.to_param}, valid_session
      }.to change(Tabelageral, :count).by(-1)
    end

    it "redirects to the tabelagerals list" do
      tabelageral = Tabelageral.create! valid_attributes
      delete :destroy, {:id => tabelageral.to_param}, valid_session
      response.should redirect_to(tabelagerals_url)
    end
  end

end
